---
packages:
  - ansible
  - autoconf%2.69
  - firefox
  - git
  - gtar--
  - i3
  - jq
  - mpv
  - mupdf--
  - mutt--sasl
  - sct
  - sysclean
  - vim--gtk3-perl-python3-ruby
  - zsh


services:
  apmd: null
  sndiod: -mplay -z 480 -b 1920
  sshd: false

sysctl:
  machdep.lidaction: 0

users:
  phy1729:
    groups:
      - _pbuild
      - dialer
      - staff
      - wheel
      - wobj
      - wsrc
    login_class: staff
    shell: /usr/local/bin/zsh
